/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as MatchFinishIdRouteImport } from './routes/match.finish.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchFinishIdRoute = MatchFinishIdRouteImport.update({
  id: '/match/finish/$id',
  path: '/match/finish/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/match/$id': typeof MatchIdRoute
  '/match/finish/$id': typeof MatchFinishIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/match/$id': typeof MatchIdRoute
  '/match/finish/$id': typeof MatchFinishIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/match/$id': typeof MatchIdRoute
  '/match/finish/$id': typeof MatchFinishIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/match/$id' | '/match/finish/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/match/$id' | '/match/finish/$id'
  id: '__root__' | '/' | '/match/$id' | '/match/finish/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchIdRoute: typeof MatchIdRoute
  MatchFinishIdRoute: typeof MatchFinishIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/finish/$id': {
      id: '/match/finish/$id'
      path: '/match/finish/$id'
      fullPath: '/match/finish/$id'
      preLoaderRoute: typeof MatchFinishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchIdRoute: MatchIdRoute,
  MatchFinishIdRoute: MatchFinishIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
